### This config file contains required core defaults that must be set, along with a handful of common optional settings.
### For a full list of available settings, see https://microsoft.github.io/graphrag/config/yaml/

### LLM settings ###
## There are a number of settings to tune the threading and token limits for LLM calls - check the docs.

models:
  default_chat_model:
    type: openai_chat
    model: deepseek-chat
    encoding_model: "cl100k_base"
    api_key: sk-44462c9146e5429f8d38c851879561a6
    api_base: https://api.deepseek.com/v1
    model_supports_json: true
    concurrent_requests: 25
    max_retries: 10
    max_retry_wait: 10.0
    tokens_per_minute: 150000
    requests_per_minute: 10000
  default_embedding_model:
    type: openai_embedding
    model: text_embedding
    encoding_model: "cl100k_base"
    api_key: c9e6e445cb2f40d6bb37fec350cd4e90.jtW9sJOjZpWTkP2V
    api_base: https://open.bigmodel.cn/api/paas/v4
    concurrent_requests: 25
    max_retries: 10
    max_retry_wait: 10.0

### Input settings ###

input:
  type: file
  file_type: text
  file_pattern: ".*\\.(txt|md|m)$"
  base_dir: "input"
  encoding: "utf-8"

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]

### Output/storage settings ###
## If blob storage is specified in the following four sections,
## connection_string and container_name must be provided

output:
  type: file
  base_dir: "output"
    
cache:
  type: file
  base_dir: "cache"

reporting:
  type: file
  base_dir: "logs"

vector_store:
  default_vector_store:
    type: lancedb
    db_uri: output/lancedb
    container_name: default
    overwrite: true

### Workflow settings ###

embed_text:
  model_id: default_embedding_model
  vector_store_id: default_vector_store

extract_graph:
  model_id: default_chat_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  model_id: default_chat_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false
  model_id: default_chat_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  model_id: default_chat_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

embed_graph:
  enabled: false

umap:
  enabled: false

snapshots:
  graphml: false
  embeddings: false

### Query settings ###
## The prompt locations are required here, but each search method has a number of optional knobs that can be tuned.
## See the config docs: https://microsoft.github.io/graphrag/config/yaml/#query

local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"

basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"

# GraphRAG 配置
api_key: "sk-44462c9146e5429f8d38c851879561a6"
llm_model: "deepseek-chat"
embedding_model: "zhipu-embedding"
embedding_api_key: "c9e6e445cb2f40d6bb37fec350cd4e90.jtW9sJOjZpWTkP2V"

# 索引配置
indexing:
  chunk_size: 1200
  overlap: 100
  max_tokens: 2048
  discover_entity_types: true
  min_examples_required: 2
  n_subset_max: 300
  k: 15

# 搜索配置
search:
  n_results: 10
  community_level: 1
  response_type: "json"
  dynamic_community_selection: true
